[tool.poetry]
name = "pythoneda"
version = "0.0.1-alpha.1"
description = ""
authors = ["rydnr <github@acm-sl.org>"]
readme = "README.md"
packages = [{include = "src/domain"}, {include = "src/infrastructure"}, {include = "src/application"}]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.28.1"
grpcio = "^1.41.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
generate-grpc = "scripts.make_grpc:main"
